# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4d5af90deb31547f1a36c073c0a579ba85ade39982b535d5efa8536e82396f3b6bdf877f82876caae59162ec68f6bbebdab7738bc6633ae4a876509227b5318

test:
  secret_key_base: e88dc13ffeaac9fadf1f99514abb2ff915f60dde2e33abb194cdde1ebbe6efbb47792cf08f78968b3d3fc72150032b7e09a3614b5d7c3870f8f4dd738e7aff39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
